name: ZOFE trampos
description: curadoria em oportunidades de trabalho
meta_description: "Vagas de trabalho em desenvolvimento web curadas por Daniel Filho."

markdown: kramdown
pygments: true
logo: false
paginate: 15

# links
baseurl: http://zofe.com.br/trampos
permalink: /:year-:month-:day-:title
relative_permalink: false

# Details for the RSS feed generator
url:            'http://zofe.com.br/trampos'
author:         'Zone of Front-Enders'
